name: ThatGuySam
favicon: null
layout_spectrum: 0.46814672322943807
typography_spectrum: 0.5407309015281498
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191b1f'
    - '#305c9c'
    - '#d53770'
    - '#22c8f9'
    - '#6f2540'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
